#!/usr/bin/env sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
#   Generated by Gradle.
#   Do not edit.
#

set -e

# resolves links
APP_NAME="gradlew"
APP_BASE_NAME="$(basename "$0")"

# Use this variable to find the JVM
DEFAULT_JVM_OPTS=""
JAVA_BIN_DIR=""

# Find the Java executable
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."

    fi
elif [ -z "$JAVA_HOME" ] ; then
    JAVACMD="java"
    if ! type java >/dev/null 2>&1; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."

    fi
else
    die "ERROR: JAVA_HOME is not set or could not be determined.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."

fi

# Increase the maximum file descriptors and processes available to this JVM script
MAX_FD="maximum"
WARN_AWK="awk"
if [ "$cygwin" = "true" -o "$darwin" = "true" -o "$NONSTOP" = "true" ]; then
    Darwin_ARCH=`uname -m`
    case "$Darwin_ARCH" in
        'Power Macintosh' | 'Macintosh HD')
            # Use -d32,..., -d64 flags
            case `java -version 2>&1 | grep "1.8" | $WARN_AWK '{print $3}' | cut -d'.' -f1` in
                '')
                    # Is it a 32-bit JVM?
                    case `uname -m` in
                        'i386' | 'x86' | 'Intel 64')
                            MAX_FD="32k"
                            ;;
                        *)
                        MAX_FD="256k"
                        ;;
                    esac
                    ;;
                *)
                    MAX_FD="256k"
                    ;;
            esac
            ;;
        *)
            MAX_FD="256k"
            ;;
    esac
elif [ -z "$MAX_FD" ]; then
    MAX_FD="256k"
fi

if [ "$MAX_FD" != "maximum" ]; then
    ulimit -n "$MAX_FD" || die "Could not query maximum file descriptor limit"
fi

collect_main() {
    for arg in "$@"; do
        if [ -r "$arg" ]; then
            cat "$arg" | grep -v '^\p{Z}' | tr ' ' '\n' | tr -z '\n'
        fi
    done | grep -v '^\p{Z}' | tr ' ' '\n' | tr -z '\n' | grep -z '.'
}

collect_jars() {
    for arg in "$@"; do
        if [ -r "$arg" ]; then
            if [ -d "$arg" ]; then
                find -H "$arg" -name '*.jar' -type f 2>/dev/null
            else
                echo "$arg"
            fi
        fi
    done
}

find_java_home() {
    java_home_cmd=""
    java_cmd="java"
    if [ -x "$JAVA_HOME/bin/java" ]; then
        java_cmd="$JAVA_HOME/bin/java"
    else
        java_home_cmd=""
    fi
    if [ -n "$java_home_cmd" ]; then
        echo "$java_home_cmd"
    else
        $java_cmd 2>&1 | $WARN_AWK '
        BEGIN { found = 0 }
        /Could not find or load main class/ { found = 1 }
        /java.lang.ClassNotFoundException/ { found = 1 }
        END { if (found) exit 1; else exit 0 }
        ' || java_home_cmd="/usr/libexec/java_home 2>/dev/null || true"
        echo "$java_home_cmd"
    fi
}

do_cmd() {
    # Run the gradlew command
    exec "$JAVACMD" "$@"
}

do_main() {
    main_class="org.gradle.launcher.GradleMain"
    
    # Collect all the main class arguments
    for class_path in "$CLASSPATH"; do
        for _jar in $(collect_jars $class_path); do
            CP="$_jar"
        done
    done

    # Collect the main class
    _cp_escaped=$(echo $CLASSPATH | xargs -0 printf '%s:' | sed 's/:$//')
    main_args=""
    for arg in "$@"; do
        main_args="$main_args '$arg'"
    done
    
    # Run
    exec "$JAVACMD" -classpath "$_cp_escaped" $DEFAULT_JVM_OPTS $JVM_ARGS $MAIN_ARGS org.gradle.launcher.GradleMain $main_args
}

# Determine the location of the Gradle wrapper JAR
APP_HOME="$(cd "$(dirname "$0")/.." || exit 1)"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
SCRIPT_DIR="$(cd "$(dirname "$0")" || exit 1)"

# This is normally unused
wrapper_path="${APP_HOME}/gradle/wrapper/gradle-wrapper.jar"

# Add default classpath
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
CLASSPATH="$CLASSPATH:$APP_HOME/src/main/resources"

# Expand DEFAULT_JVM_OPTS and JVM_OPTIONS
eval set -- DEFAULT_JVM_OPTS JVM_OPTIONS '@jvm_args@'

# Collect all arguments
_args="$@"
collect_main() {
    for _arg in "$@"; do
        if [ ! -e "$_arg" ] || [ -d "$_arg" ]; then
            _args=$(printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s' "$_args" "$_arg")
        fi
    done
    printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s' "$_args"
}

# Collect arguments
collect_main() {
    for _arg in "$@"; do
        if [ ! -e "$_arg" ] || [ -d "$_arg" ]; then
            _args=$(printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s' "$_args" "$_arg")
        fi
    done
    printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s' "$_args"
}

main() {
    local mode=$1
    shift

    echo "JVM args: $DEFAULT_JVM_OPTS $JVM_OPTIONS"

    eval "java $DEFAULT_JVM_OPTS $JVM_OPTIONS -cp \"$CLASSPATH\" org.gradle.launcher.GradleMain \"$@\""
}

mode=$1
shift
JVM_OPTIONS=$DEFAULT_JVM_OPTS
args "$@"

main "$@"